import { motion } from 'motion/react';
import Navbar from './Navbar';
import Footer from './Footer';

const Terms = () => {
  return (
    <div className="relative w-full min-h-screen bg-black noise-overlay">
      <div className="absolute inset-0 grid-bg opacity-30"></div>
      <Navbar />

      <div className="relative z-10 max-w-[720px] mx-auto px-6 pt-[140px] pb-[100px]">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-[36px] md:text-[48px] font-medium leading-[1.08] tracking-[-2px] text-white mb-3">
            Terms of Service
          </h1>
          <p className="text-white/30 text-[15px] mb-12">Effective Date: February 20, 2026</p>

          <div className="space-y-10 text-white/50 text-[15px] leading-[1.8]">
            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using Bloxr ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">2. Description of Service</h2>
              <p>Bloxr is an AI-powered development tool that helps users create Roblox games using natural language prompts. The Service generates Lua code and interacts with Roblox Studio via a plugin.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">3. Eligibility</h2>
              <p>You must be at least 13 years old to use Bloxr. If you are under 18, you must have parental or guardian consent.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">4. User Accounts</h2>
              <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">5. Acceptable Use</h2>
              <p>You agree not to use Bloxr to: generate malicious code, violate Roblox's Terms of Service, infringe on intellectual property rights, or engage in any unlawful activity.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">6. AI-Generated Content</h2>
              <p>Bloxr uses AI to generate code and content. We do not guarantee the accuracy, completeness, or fitness of any AI-generated output. You are solely responsible for reviewing and using any generated code.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">7. Intellectual Property</h2>
              <p>Code generated by Bloxr on your behalf belongs to you. Bloxr retains all rights to the platform, branding, and underlying technology.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">8. Subscription and Billing</h2>
              <p>Paid plans are billed on a subscription basis. Refunds are issued at our discretion. We reserve the right to change pricing with 30 days notice.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">9. Termination</h2>
              <p>We reserve the right to suspend or terminate your account at any time for violation of these terms or for any other reason at our sole discretion.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">10. Disclaimer of Warranties</h2>
              <p>The Service is provided "as is" without warranties of any kind, express or implied.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">11. Limitation of Liability</h2>
              <p>To the fullest extent permitted by law, Bloxr shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">12. Changes to Terms</h2>
              <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
            </div>

            <div>
              <h2 className="text-white text-[18px] font-semibold mb-3">13. Contact</h2>
              <p>For questions about these Terms, contact us at <a href="mailto:legal@bloxr.dev" className="text-[#4F8EF7] hover:text-[#4F8EF7]/80 transition-colors">legal@bloxr.dev</a>.</p>
            </div>
          </div>
        </motion.div>
      </div>

      <Footer />
    </div>
  );
};

export default Terms;
